[package]
name = "passtui"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30"
crossterm = "0.29"
arboard = { version = "3.6", features = ["wayland-data-control"] }
walkdir = "2"
dirs = "6"
anyhow = "1"
rand = "0.10"
zxcvbn = "3"
serde = { version = "1", features = ["derive"] }
toml = "0.9"
zeroize = "1.8"
